image: nexus.itecos.com:5000/java-app:15

stages:
  - build

build:
  image: nexus.itecos.com:5000/sbt-docker-build-13:0.1
  stage: build
  before_script:
    - git branch
    - docker -v
  script:
    - sbt "project orcTelegramBot" docker
    - docker image ls
